apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - image: tsubasaxzzz/util-container
          name: init-nginx
          command:
            ["sh", "-c", 'echo "<h1>"$(uname -n)"</h1>" > /data/index.html']
          volumeMounts:
            - mountPath: /data
              name: html-volume
      containers:
        - image: tsubasaxzzz/util-container
          name: util-container
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-volume
      terminationGracePeriodSeconds: 180
      volumes:
        - name: html-volume
          emptyDir: {}
