apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testpod
  name: testpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpod
  template:
    metadata:
      labels:
        app: testpod
    spec:
      initContainers:
        - image: tsubasaxzzz/util-container
          name: init-nginx
          command:
            ["sh", "-c", 'echo "<h1>"$(uname -n)"</h1>" > /data/index.html']
          volumeMounts:
            - mountPath: /data
              name: html-volume
      containers:
        - image: tsubasaxzzz/util-container
          name: util
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-volume
          livenessProbe :
            exec:
              command:
              - /bin/bash
              - -c
              - test ! -e /purge.dat
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe :
            exec:
              command:
              - /bin/bash
              - -c
              - test ! -e /purge.dat
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash","-c", "touch /purge.dat;sleep 50;nginx -s quit"]
      terminationGracePeriodSeconds: 60
      volumes:
        - name: html-volume
          emptyDir: {}
